version: 1.0.{build}

branches:
  only:
    - build

skip_tags: true

skip_commits:
  message: /^(?!Upgrade windows)/

os: Visual Studio 2015

clone_folder: c:\projects\sublime_sassc

environment:
  gh_token:
    secure: MvdJfQB+M4J/YSrgz423k/4Q6U+OQTA7D5KGzWayeEctNlAeRGh8ybIlvol0QU8D

install:
    - ps: |
        $VSN = $env:APPVEYOR_REPO_COMMIT_MESSAGE.split('v')[1]
        git checkout master 2>$null
        cmd /c "build.bat $VSN -m64"
        cp sassc.exe st2_windows_x32\
        cp sassc.exe st3_windows_x32\
        rm sassc.exe
        cmd /c "build.bat $VSN -m64"
        cp sassc.exe st2_windows_x64\
        cp sassc.exe st3_windows_x64\
        rm sassc.exe

build: off
test: off
deploy: off

on_success:
    - ps: |
        git config --global user.name "Ben Krieger"
        git config --global user.email blitzrk@gmail.com
        git add st2*
        git add st3*
        git commit -m "Upgraded windows to v$VSN"
        $err = $(git push "https://$($env:gh_token)@github.com/blitzrk/sublime_sassc.git" master 2>&1)
        if($err -like '*rejected*') { 
            throw $err
        }
